In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_json('./yelp/yelp_academic_dataset_checkin.json', lines=True)
checkins_freq_df = df[['business_id']].copy()
checkins_freq_df['frequency'] = df['date'].str.count(',')+1
checkins_freq_df.head()

              business_id  frequency
0  --0r8K_AQ4FZfLsX3ZYRDA          1
1  --0zrn43LEaB4jUWTQH_Bg          9
2  --164t1nclzzmca7eDiJMw        311
3  --2aF9NhXnNVpDV0KS3xBQ          8
4  --2mEJ63SC_8_08_jGgVIg          4

In [3]:
df = pd.read_json('dataset/yelp_academic_dataset_business.json', lines=True)
df = pd.merge(checkins_freq_df, df[['business_id', 'stars']], on='business_id')
df.head(3)

              business_id  frequency  stars
0  --0r8K_AQ4FZfLsX3ZYRDA          1    5.0
1  --0zrn43LEaB4jUWTQH_Bg          9    1.0
2  --164t1nclzzmca7eDiJMw        311    4.0

In [4]:
df[['frequency', 'stars']].corr()

           frequency     stars
frequency   1.000000  0.015111
stars       0.015111  1.000000

In [5]:
df['stars'].value_counts()

4.0    30876
3.5    26516
4.5    24612
3.0    19792
5.0    13511
2.5    12191
2.0     7310
1.5     3202
1.0      866
Name: stars, dtype: int64

In [6]:
user_df = pd.read_json('dataset/yelp_academic_dataset_user.json', lines=True,
                       dtype = {
                           "user_id": str,
                           "name": str,
                           "review_count": int,
                           "yelping_since": str,
                           "useful": int,
                           "funny": int,
                           "cool": int,
                           "elite": str},
                       chunksize=500000) # if you have less available memory, please change the size into a smaller one. It took me ~7.1GB at its peak at this chunksize.

# There are multiple chunks to be read
chunk_list = []
for chunk in user_df:
    chunk_list.append(chunk[['user_id', 'friends']].copy())
new_df = pd.concat(chunk_list, ignore_index=True, axis=0)

In [7]:
new_df

,user_id,friends
0,q_QQ5kBBwlCcbL1s4NVK3g,"xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg..."
1,dIIKEfOgo0KqUfGQvGikPg,"XPzYf9_mwG2eXYP2BAGSTA, 2LooM5dcIk2o01nftYdPIg..."
2,D6ErcUnFALnCQN4b1W_TlA,"GfB6sC4NJQvSI2ewbQrDNA, jhZtzZNNZJOU2YSZ6jPlXQ..."
3,JnPIjvC0cmooNDfsa9BmXg,"HQZPQhKMwRAyS6BCselVWQ, kP2U1s_sjQfHO9grxiyDTA..."
4,37Hc8hr3cw0iHLoPzLK6Ow,"-Q88pZUcrfN0BLBDp-bkAQ, etPn4Pv1Gc4cRZjRgB_BOw..."
5,n-QwITZYrXlKQRiV30MqNg,"2ptwW5l68069vNtW8J-WOg, 4TVFuz8L4TsDtx_ObSin9g..."
6,eCJoZqpV1fDKJGAsXmWXqQ,"DlT1HhrcYfDhjJNUyskU5g, C0ly5C7RzTlzh0M55YspDw..."
7,cojecOwQJpsYDxnjtgzteQ,"_Tpd51CSlnOyvDTpOtgG5w, jVYzrVblDFSuL3GHtt8ZSA..."
8,1jXmzuIFKxTnEnR0pxO0Hg,"VGfzq5na6LZUwxwWO5eVLA, 35uHDsVOEsWbLdEg8Ttobg..."
9,-8QoOIfvwwxJ4sY201WP5A,"vePby1OhpTiQiX75XrN97A, UG8cewYtZdep2hzSekIqYg..."
10,EtofuImujQBSo02xa6ZRtQ,"8z3hZO0SE75e6kO2Bsm8pA, bRHT_AP9l_HNgGsX4PnDiw..."
11,cxS6dbjyPgPS1S890u_khA,"ISN91YL7nkU_X_bovO2Lyg, sxsXw8QrbFTUzVVGGLNdOg..."
12,MUzkXfPS9JaMgJ907orz0g,"dyfc7mHf52_EKUBPHJ1NJw, 4gAD7fnWZNYP3TIMJGyt5A..."
13,tjwblGkWN9m0vsGaypJ0Vw,"fv54kCf31SFX0_5IX4klYg, pH3Glr-87CaV_w4mv3ZB5w..."
14,m-zIVssiXN4bnDFqMdPtEA,"kwFrKHPFRhsVC-giWwA2PA, sa3iJuVNk3GnHiN3WeRT9A..."
15,fxqvyXlml4400BglsxRG_w,"ZsyckIBtw1CzIpW6Sg0JnA, PQOHkTVWUoAxAkiUa3SRMg..."
16,9edAbpniyhHFdpAvknQPBg,"Nu0ar5uqyK7nqdDE7Re7mg, 7q7Z1yVQ1PqrDqrZ1C-Iyg..."
17,wURnB9fRNGAli13yBwhENA,"dGhopA16w5DzgZdnUUkJ2Q, HFECrzYDpgbS5EmTBtj2zQ..."
18,l4P65LXNBnJqI7oTXdBvGg,"s1Hsu9cFf5qJym5-ujO2MQ, o-f-5l7EonuIRzCTwE_OmQ..."
19,9RIXlhUb_xEVuc_o0QsT0w,"Hir63JDPRIwdqy2yiwJPmw, VH7Ch3yvatvELkCsu8EnrA..."
20,QJI9OSEn6ujRCtrX06vs1w,"RyPeT_ICAtX8ah9dhDpEFw, W8r4aKPZFT3GPIQQDbqB6Q..."
21,BBSYyLG824fZjP-kulhLgw,"vp3ZJlr4YT4wfRSUPtv7UA, KaOlyjI_VYZ8Ccmhf-BE8Q..."
22,tYSq-W6abB0azvTNdvCpGQ,"S5DGX7S0HsBw01a7R1ZAEg, 7gY2o5VoLDIz1KJfghWu1A..."
23,NXdRSIvNt_CUipRaJy29nw,"oi2YM1adhZZMBEq0jIbJ9A, 2VKyT3D4i3MG7C7FuPIknA..."
24,s40p6DP3uX822EfcReLdOg,"6UTikTMgT13yDoEsfHpqJQ, BE2GER1YIwdq_wxlJ_PPBg..."
25,8J5gkxtQPyZcG_JFzqgQUw,"k8y-QweWej-XTHaNjB6SDA, k0bU1uqUsbWHI297E3x5uw..."
26,EeKFz5FcrlajMbm0tyFn7Q,"wPMb_4uxjKf6zx1bhOdm3Q, Btp0lvpPil3Vq-vt180x1A..."
27,sZo-AQkZgrcBjYKFlfB5nQ,"F5sYaQH4yDx8ngjKRs4V-g, 1yI_og9nSF_LaGj1iCncUA..."
28,ZmB_g5aBc1KB7YeOsp3HIg,"b2D6PSdwEoitpCGufAUiNg, zlsZjH76jWTXiG7fyyUzEw..."
29,-oZ0Qva3U8W_HXKAVvscLQ,"J6vBnK8r0uDTLu_NK1AQQQ, 7pfOB3sBYxgP48N_6XNUrQ..."
...,...,...
2189427,_O8o9cY94Z8vpv2NbEiu6A,None
2189428,mCRkWI5vucGBTN85ZFyKVQ,None
2189429,I312vuA3Mc_QsTP4uTMBAg,None
2189430,2OZtUWHLrQ-dt3g-ETYLMA,None
2189431,wbeSyrKkbXT9MkYAeGfDVA,None
2189432,PgXcXf0Y7C42tZ7fdtfHAw,None
2189433,H-LkyWi_1KGKVa54vcKjnA,None
2189434,bGQk6RDBX4fFO4sD006AVQ,None
2189435,8ssdlnaO1z6x3LGAuf5eoQ,None
2189436,C33SBnJ7PaBzHHeIdfsBOg,None
2189437,0LXQ0tQ1OY4aSuUlV-in2w,None
2189438,9YU3omo0BUrEG0bn9lPTIw,None
2189439,VQCmywqijMCn9ugg692gyQ,None
2189440,yuV2wow6B52ydYg-hv22Cw,None
2189441,1Emq5RHo1By-yWrA7nV1-g,None
2189442,GRZMubFxFhTPs-rZEWFu6A,None
2189443,XjxPrwv8CGAb83bCwjVwGg,None
2189444,9GN5U-Jh-2WF_4L0OrGdfA,None
2189445,XE__rFfuZRdJkRa8nz4eiA,None
2189446,fuC01HUN_tKPQd86S4EhkA,None
2189447,sQ0PPwfoK-gpe4OVnfi4Eg,None
2189448,OIOZBaJeLhhI9FcvwsDYvQ,None
2189449,y_sOV2_gVVwqKEWpnOI9Qw,None
2189450,_B516W49A83XEVsE2Zcj6w,None
2189451,LqsufFyOWnW1GMp5GsZJJg,None
2189452,OrXXOTSQG2hLEoZ4sw03Gg,None
2189453,pYZ4Dyx5I92u5gDfGiVTpQ,None
2189454,DhrXTJRTLhnvI9UI1q63mg,None
2189455,ka06dBaC9tvKhc7DJ9_7wQ,None
2189456,QfkFTrJ_MdM3Onk6przUJw,None

In [8]:
tmp_df = new_df.copy()

In [9]:
friend_freq = tmp_df['friends'].apply(lambda x: 0 if x == 'None' else x.count(',')+1)

In [ ]:
fig = px.histogram(friend_freq, log_y=True)
fig.show()

In [11]:
print('sum(friend_freq != 0) / len(friend_freq) =', sum(friend_freq != 0), '/', len(friend_freq), '=', sum(friend_freq != 0) / len(friend_freq))

sum(friend_freq != 0) / len(friend_freq) = 1233453 / 2189457 = 0.5633602304132943